### ISSUE TITLE
There is no Video to scrobble

### ISSUE THREAD

**Issue by Feuerforst** [floblik/YouScrobbler#10]
Hey,

since the 1.4 Version of YouScrobbler it`s only working with the first Titel.
After that the Scrip is not working anymore. 
When Youtube starts the next Video with Autoplay the Addon says "There is no Video to scrobble" and the Button is greyed out

If i press F5 its works, but again only for this track.

Firefox 51.0.1 (64-Bit)
Greasemonkey 3.10

**Comment by Feuerforst** [comment]
i noticed that when the 2nd Song is playing and the Script is not Scrobble, the Script pops up and wanna start scrobbeling, when the Song is over and the Youtube autoplay Timer is starting.  But that obviously to late.

**Comment by floblik** [comment]
> i noticed that when the 2nd Song is playing and the Script is not Scrobble, the Script pops up and wanna start scrobbeling, when the Song is over and the Youtube autoplay Timer is starting. But that obviously to late.

If you pause and resume the 2nd song does that make a difference?

**Comment by floblik** [comment]
Ok, think I found the problem. Please check version 1.4.2

**Comment by Feuerforst** [comment]
Thx, i will give it a try but at the Moment i get this Error:
Error: Error occured while connecting to Last.FM Api

doesn`t matter if i use 1.4.1 or 1.4.2. 
i also used the Reset Auth function and i also reinstalled the script.

**Comment by Feuerforst** [comment]
Perfect. 
it`s perfect working now.
thx
