### ISSUE TITLE
Scrobbles song as it finishes

### ISSUE THREAD

**Issue by Nerdthe5th** [floblik/YouScrobbler#14]
The autoscrobble timer starts when the song begins on youtube for about 120 seconds or so. The song isn't actually scrobbled until this timer ends. Here are a few pictures of what I see.

Thanks
![screenshot 7](https://user-images.githubusercontent.com/30054814/28032968-ff07bb1e-6571-11e7-9d75-4b284f5db38c.png)
![screenshot 8](https://user-images.githubusercontent.com/30054814/28032969-009e04c4-6572-11e7-9f86-af53f1c39cb3.png)
![screenshot 9](https://user-images.githubusercontent.com/30054814/28032970-01ec0182-6572-11e7-999f-9920c0c45650.png)
![screenshot 10](https://user-images.githubusercontent.com/30054814/28032971-02e00bf6-6572-11e7-800c-6dcd4961c888.png)

**Comment by floblik** [comment]
@Nerdthe5th Yes, this behaviour is right. The song can only be scrobbled after actually playing the video. In the settings you can adjust at what percentage of the video the scrobble should be done.

**Comment by Nerdthe5th** [comment]
Oh okay, thank you for that, I'm so blind lol. Sorry I brought this up
