### ISSUE TITLE
Does not work with firefox 57

### ISSUE THREAD

**Issue by erdnaxeli** [floblik/YouScrobbler#18]
The scrobbler button on the YouTube page is grey, like it was disabled.

**Comment by jtojnar** [comment]
Greasemonkey 4 uses a new Promise based API https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html

**Comment by duri2** [comment]
@jtojnar is right, it's problem with Greasemonkey 4 (web extensions). Try Tampermonkey - everything works fine.

**Comment by floblik** [comment]
Yes, its a problem with Greasemonkey. Please use Tampermonkey instead.

**Comment by jtojnar** [comment]
Or you can use [Violentmonkey](https://github.com/violentmonkey/violentmonkey), if you prefer open-source solutions.
