### ISSUE TITLE
Songs double scrobbling in Firefox with third-party addons enabled

### ISSUE THREAD

**Issue by depwl9992** [floblik/YouScrobbler#6]
It seems as though the script is double-scrobbling, often with one second separation between the events.

I cannot positively replicate the problem with any known set of steps as sometimes I have two entries in my list, and sometimes I don't. However, it seems to occur only when certain Firefox addons such as "Download Youtube Videos as MP4" and "Flash and Video Download" activate/create buttons on the page which may be clashing with Youscrobbler - I have not seen any double scrobbling when these are disabled.

I did notice that despite the configuration setting "Scrobble at ##%", the song is logged immediately upon page load, and and am speculating when the other addons draw their objects, they may trigger a partial page refresh of some sort which youscrobbler would have a chance at detecting.

Using Firefox 41.0.1 with Greasemonkey 3.4.1.

**Comment by maturanomx** [comment]
Exactly same behavior, but I don't have any of the mentioned extensions. Firefox 42.0 with Pentadactyl  1.2pre and Greasemonkey 3.6

**Comment by nomicode** [comment]
I am getting duplicate scrobbles for every track I listen to on YouTube. Using Chrome with no extensions except Tampermonkey.

**Comment by floblik** [comment]
Are you still experiencing the same problem with newest update?

**Comment by depwl9992** [comment]
Seems YS 1.4.4 no longer has this issue. Will re-open the ticket if I see it again though!
