### ISSUE TITLE
'Auto' scrobbles on opening instead of 75% of play time

### ISSUE THREAD

**Issue by cipri-tom** [floblik/YouScrobbler#7]
Hi,

The plugin works pretty well and I'm overall satisfied with it. However, there's a small annoyance on Firefox 44 (haven't tried other browsers) as it scrobbles a song as soon as it is opened instead of waiting until it has some play time.

Great work! Thank you for the effort of maintaining this!

**Comment by floblik** [comment]
Hi,

Is the scrobble sended to last.fm directly at the begining of the video? (And you can see it on your last.fm profile?)
Or is it appearing in your profile after 75% with an annotation like "3 minutes ago"?

**Comment by cipri-tom** [comment]
Thanks for taking time to look into it! 

It is sent directly as soon as the page is loaded :(.

**Comment by tobbez** [comment]
Might be some issue with how default settings are handled.

I never had this problem in my older install of YouScrobbler (in Firefox), but it happened in a more recent install (in Chrome w/ Tampermonkey).

Changing the "scrobble at" setting to something else and then back to 75% seems to fix it.

**Comment by cipri-tom** [comment]
indeed, changing the setting fixes it. Thank you, @tobbez !
