### ISSUE TITLE
Constant "Track not found on LastFM" issue

### ISSUE THREAD

**Issue by michelekappa** [floblik/YouScrobbler#9]
Whenever a tune is listened, with the autoscrobble feature on, youscrobbler responds with "Track not found on lastfm". Fields are already filled in, and manual scrobbling works fine.
Tunes are obviously present on LastFM.
Version 1.4, Firefox 51.01.1 32bit, Greasemonkey 3.10.

This issue started with the 1.4 update.

**Comment by michelekappa** [comment]
Firefox restart solved the issue.

**Comment by michelekappa** [comment]
Nevermind, issue is still here.
After Firefox restart, autoscrobble worked on a song that had already been manually scrobbled. Next not already manually scrobbled track pops up "Track not found on LastFM" again.

**Comment by floblik** [comment]
Please check if the update fixes the issue for you.

**Comment by michelekappa** [comment]
Works. Fastest hotfix on the planet. :)
Closing.
